# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Import Dataset

In [2]:
df = pd.read_csv('../data/raw-data/train.csv')

In [3]:
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.7980
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.3680
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.1880
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.3760
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.3840

# About the Data

In [4]:
df.shape

(9800, 18)

In [5]:
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
5334,5335,CA-2015-103331,26/08/2015,01/09/2015,Standard Class,KB-16315,Karl Braun,Consumer,United States,Newark,Delaware,19711.0,East,OFF-PA-10002160,Office Supplies,Paper,Xerox 1978,17.340
7562,7563,US-2017-104815,03/09/2017,07/09/2017,Standard Class,RB-19570,Rob Beeghly,Consumer,United States,Chicago,Illinois,60610.0,Central,FUR-BO-10003894,Furniture,Bookcases,"Safco Value Mate Steel Bookcase, Baked Enamel ...",198.744
169,170,CA-2015-139892,08/09/2015,12/09/2015,Standard Class,BM-11140,Becky Martin,Consumer,United States,San Antonio,Texas,78207.0,Central,OFF-AP-10002518,Office Supplies,Appliances,Kensington 7 Outlet MasterPiece Power Center,177.980
7528,7529,US-2018-106145,26/09/2018,26/09/2018,Same Day,RA-19885,Ruben Ausman,Corporate,United States,San Francisco,California,94109.0,West,OFF-PA-10002245,Office Supplies,Paper,Xerox 1895,35.880
2162,2163,CA-2018-166296,13/03/2018,19/03/2018,Standard Class,KF-16285,Karen Ferguson,Home Office,United States,Manteca,California,95336.0,West,OFF-PA-10004359,Office Supplies,Paper,Multicolor Computer Printout Paper,314.550

In [6]:
df['Country'].unique()

<StringArray>
['United States']
Length: 1, dtype: str

---

By my observation, research and by doing some operations on dataset I get to know that....
The dataste contains the superstore sales data. Total 9800 records with 18 columns. The data only contain the US sales data or maybe the superstore is only available at US.  
The each row in the data represents one product. If one customer purchesed the 2 products at the same time then it mentioned in the data n 2 columns, saperate entry for each product.  

It contains `Row ID`, `Order ID`, `Order Date`, `Ship Date`, `Ship Mode`,	`Customer ID`, `Customer Name`,	`Segment`, `Country`, `City`, `State`, `Postal Code`, `Region`,	`Product ID`, `Category`, `Sub-Category`, `Product Name` & `Sales`. These are in total 18 columns.

# Columns descriptions

In [8]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

---

**`superstore-sales`**

`Row ID` - It is just a number representing the row number. We have 9800 rows.  
`Order ID` - It is the order ID, It is the same for those product which are ordered at the same time by the same customer.  
`Order Date` - The date of ordered is in the Order Date column  
`Ship Date` - This column contains the date. The date is of the day on which the product is delivered to customer.  
`Ship Mode` - Ship mode column contains the string values. Which have represents the shiping mode of the product.  
`Customer ID` - Customer ID in alphanumeric code. This is the combination of name and surname initials with a unique code concatinated with '-'  
`Customer Name` - Name of the customer.  
`Segment` - This column contains the user segment. The customers are splited into 3 groups. (**Consumer**: Regular people buying things for themselves. **Corporate**: Big companies buying things for their offices. **Home Office**: People who work from home buying things for their workspace.)  
`Country` - Country name which is only United States.
`City` - It has the city name. Where the customer is live or package is delivered.  
`State` - The state.  
`Postal Code` - The postal code.  
`Region` - The US geographical area is splited into 4 parts (Central, East, South & West)  
`Product ID` - It is the unique id for each product. It is like (category-subcategoey-uniquecode)  
`Category` - It has the category of the product. (ex. Furniture, Offie Supplies, Art, ...etc)  
`Sub-Category` - It has the sub-category of the product. (ex. Bookcases, chair, Table, ...etc)  
`Product Name` - The actual name of the product by the brand.
`Sales` - It is the price of the product.

# Assessment

## Check by eyes
Take a look at any unusual data in the dataset by eyes

In [12]:
# Lets run sample command to get random rows and study them
df.sample(5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
5756,5757,CA-2015-163748,14/10/2015,18/10/2015,Standard Class,HG-15025,Hunter Glantz,Consumer,United States,Fort Worth,Texas,76106.0,Central,TEC-CO-10002095,Technology,Copiers,Hewlett Packard 610 Color Digital Copier / Pri...,1999.960
8705,8706,US-2015-132745,01/10/2015,05/10/2015,Standard Class,NF-18475,Neil Französisch,Home Office,United States,Reno,Nevada,89502.0,West,OFF-FA-10000254,Office Supplies,Fasteners,Sterling Rubber Bands by Alliance,4.710
3044,3045,CA-2016-135174,30/04/2016,02/05/2016,Second Class,BP-11230,Benjamin Patterson,Consumer,United States,Troy,Ohio,45373.0,East,TEC-PH-10001530,Technology,Phones,Cisco Unified IP Phone 7945G VoIP phone,1022.970
2849,2850,CA-2017-123617,28/11/2017,03/12/2017,Standard Class,AJ-10780,Anthony Jacobs,Corporate,United States,Palm Coast,Florida,32137.0,South,OFF-BI-10002976,Office Supplies,Binders,ACCOHIDE Binder by Acco,7.434
8299,8300,US-2015-103338,11/03/2015,15/03/2015,Standard Class,RB-19435,Richard Bierner,Consumer,United States,Roseville,California,95661.0,West,OFF-AR-10001770,Office Supplies,Art,Economy #2 Pencils,7.980

### Problems found

The column names should be changed, remove the spaces.

---

## Check by info()
Lets check data types of all columns

In [14]:
# info to chack data types of the columns
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 1.3 MB

In [21]:
# Check for Categorical columns 
df['Ship Mode'].unique(), df['Segment'].unique(), df['Region'].unique(), df['Category'].unique(), df['Sub-Category'].unique()

(<StringArray>
 ['Second Class', 'Standard Class', 'First Class', 'Same Day']
 Length: 4, dtype: str,
 <StringArray>
 ['Consumer', 'Corporate', 'Home Office']
 Length: 3, dtype: str,
 <StringArray>
 ['South', 'West', 'Central', 'East']
 Length: 4, dtype: str,
 <StringArray>
 ['Furniture', 'Office Supplies', 'Technology']
 Length: 3, dtype: str,
 <StringArray>
 [  'Bookcases',      'Chairs',      'Labels',      'Tables',     'Storage',
  'Furnishings',         'Art',      'Phones',     'Binders',  'Appliances',
        'Paper', 'Accessories',   'Envelopes',   'Fasteners',    'Supplies',
     'Machines',     'Copiers']
 Length: 17, dtype: str)

### Problems Found

Here the data type of some columns are not appropriate  
1. `Order Date` and `Ship Date` should be in datetime.
2. `Postal Code` should be str. (Cause some cities have postal code with leading zeros)
3. `Ship Mode`, `Segment`, `Region`, `Category` & `Sub-Category` should be categorical.

---

## Chech by isnull()
Lets check any null values are present in the dataset

In [24]:
# Lets check null values
df.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

### Problems Found

11 rows have missing Postal codes, all other columns are good.

## Check by duplicated()
check for duplicate record in the dataset

In [27]:
# check for duplicate record.
df[df.duplicated()]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales]
Index: []

In [34]:
# Lets check without Row ID column
df.drop(columns='Row ID', inplace=True)

In [35]:
df[df.duplicated()]

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
3406,US-2015-150119,23/04/2015,27/04/2015,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372

In [37]:
# Found one duplicate record 
# Lets first check is it really a duplicate record
df[df['Order ID']=='US-2015-150119']

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
3405,US-2015-150119,23/04/2015,27/04/2015,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372
3406,US-2015-150119,23/04/2015,27/04/2015,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-CH-10002965,Furniture,Chairs,Global Leather Highback Executive Chair with P...,281.372
3407,US-2015-150119,23/04/2015,27/04/2015,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,OFF-BI-10000145,Office Supplies,Binders,Zipper Ring Binder Pockets,7.488
3408,US-2015-150119,23/04/2015,27/04/2015,Standard Class,LB-16795,Laurel Beltran,Home Office,United States,Columbus,Ohio,43229.0,East,FUR-FU-10002191,Furniture,Furnishings,G.E. Halogen Desk Lamp Bulbs,22.336

### Problem Found

It is maybe not be an duplicate record cause it is possible that the Customer named 'Laurel Beltran' ordered 2 chairs.

---

## Check by duplicated()

In [42]:
df.describe()

        Postal Code         Sales
count   9789.000000   9800.000000
mean   55273.322403    230.769059
std    32041.223413    626.651875
min     1040.000000      0.444000
25%    23223.000000     17.248000
50%    58103.000000     54.490000
75%    90008.000000    210.605000
max    99301.000000  22638.480000

No unusuall data found

---

# Documenting the Assessment

1. Column names should not contain the space. (Remove or replace spaces from the column names).
2. Incorrect Data types:
    1. `Order Date` and `Ship Date` columns have str dtype (Change it to datetime)
    2. `Postal Code` have float64 dtype (Change it to str)
    3. `Ship Mode`, `Segment`, `Region`, `Category` & `Sub-Category` have dtype str (Change it to Categorical)
3. `Postal Code` have 11 missing values (Tyr to fill it with correct values)